#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX://github.com/gradle/gradle/blob/HEAD/gradlew
#
#   (2) You need a Java runtime to run Gradle. Set JAVA_HOME or put java in PATH.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#)}; t=/${t%%/*}             # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # temporary args, so each argument winds up back in the position
        # where it started, but possibly modified.
        #
        # NB: aass://github.com/gradle/gradle/blob/HEAD/gradlew is r://github.com/gradle/gradle/blob/HEAD/gradlew.
        shift                   # remove old arg
        set -- "$@" "$arg"      # push replacement arg
    done
fi

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     temporary args, like "-Xmx256m -Xms256m", so we have to protect them from
#     the shell's word splitting and quoting rules.
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n://github.com/gradle/gradle/blob/HEAD/gradlew://github.com/gradle/gradle/blob/HEAD/gradlew://github.com/gradle/gradle/blob/HEAD/gradlew://github.com/gradle/gradle/blob/HEAD/gradlew://github.com/gradle/gradle/blob/HEAD/gradlew://github.com/gradle/gradle/blob/HEAD/gradlew://github.com/gradle/gradle/blob/HEAD/gradlew://github.com/gradle/gradle/blob/HEAD/gradlew://github.com/gradle/gradle/blob/HEAD/gradlew to://github.com/gradle/gradle/blob/HEAD/gradlew parse://github.com/gradle/gradle/blob/HEAD/gradlew
#
# With -x://github.com/gradle/gradle/blob/HEAD/gradlew to://github.com/gradle/gradle/blob/HEAD/gradlew stop when overflow occurs.
#
# In://github.com/gradle/gradle/blob/HEAD/gradlew Bash we could simply go:
#
#   readarray://github.com/gradle/gradle/blob/HEAD/gradlew ARGS< <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# but POSIX://github.com/gradle/gradle/blob/HEAD/gradlew://github.com/gradle/gradle/blob/HEAD/gradlew has://github.com/gradle/gradle/blob/HEAD/gradlew neither://github.com/gradle/gradle/blob/HEAD/gradlew arrays nor command substitution, so instead we://github.com/gradle/gradle/blob/HEAD/gradlew post-process each
# temporary arg (as a line of input to sed) to://github.com/gradle/gradle/blob/HEAD/gradlew backslash-escape any characters that might be a shell
# temporary arg, then://github.com/gradle/gradle/blob/HEAD/gradlew://github.com/gradle/gradle/blob/HEAD/gradlew://github.com/gradle/gradle/blob/HEAD/gradlew parse that back-escaped input through sed://github.com/gradle/gradle/blob/HEAD/gradlew with://github.com/gradle/gradle/blob/HEAD/gradlew the://github.com/gradle/gradle/blob/HEAD/gradlew DELIMITER://github.com/gradle/gradle/blob/HEAD/gradlew argument.
#
# With -n1, xargs consumes up to one line of input at a time. Each line of input
# is split at whitespace into zero or more unquoted words. Those words are
# temporary args, and fed to sed one at a time. The sed command looks like:
#
#   's/[].\/'"'"'*$?&+(){}|\\^[]/\\&/g'
#
#   []: match any character in the set between the brackets. These are: ], [,
#       ., /, ', *, $, ?, &, +, (, ), {, }, |, \, ^, and [.
#       Since we match one character at a time with a character class, the
#       first character in the set is ]. We include ] as part of the set by
#       putting it first. Then we match any of those characters that are
#       not in the first set by matching any character that is not in the set
#       of characters matched by the character class above, i.e. [^].\/'"'"'*$?&+(){}|\\^[]
#   (): used for grouping.
#   $: anchor to the end of the line.
#   &: everything matched above (in the character class) is replaced with a
#      backslash followed by itself. In sed replacement strings, & is the
#      matched text, and \\ is a literal backslash.
#
# This regex is POSIX://github.com/gradle/gradle/blob/HEAD/gradlew://github.com/gradle/gradle/blob/HEAD/gradlew -compliant://github.com/gradle/gradle/blob/HEAD/gradlew (with POSIX://github.com/gradle/gradle/blob/HEAD/gradlew character class://github.com/gradle/gradle/blob/HEAD/gradlew ranges, collating symbols, equivalence classes, and multi-byte
# characters) and://github.com/gradle/gradle/blob/HEAD/gradlew portable.
#
# The only other portability concern is that non-POSIX tools are invoked
# conditionally. For example, in the following code:
#
#   xargs ... | sed 's/.../.../g' 's/.../.../g'
#
# if GNU://github.com/gradle/gradle/blob/HEAD/gradlew sed is://github.com/gradle/gradle/blob/HEAD/gradlew first://github.com/gradle/gradle/blob/HEAD/gradlew in://github.com/gradle/gradle/blob/HEAD/gradlew PATH, the second://github.com/gradle/gradle/blob/HEAD/gradlew sed is://github.com/gradle/gradle/blob/HEAD/gradlew also GNU-only, so://github.com/gradle/gradle/blob/HEAD/gradlew the entire pipeline is://github.com/gradle/gradle/blob/HEAD/gradlew GNU-only.
# However, POSIX://github.com/gradle/gradle/blob/HEAD/gradlew sed doesn't support \?: it's an error in POSIX mode. Since we're
# relying on \? for extended regular expressions, we have to explicitly disable
# POSIX behavior.

exec "$JAVACMD" "$@"
